old_sound_rabbit_mq:

    producers:

        green_bc_integration_event:
            connection:       default
            exchange_options: { name: 'bc_integration_event_ex', type: topic  }


    consumers:

    multiple_consumers:
        green_integration_acl:
            connection:       default
            exchange_options: {name: 'bc_integration_event_ex', type: topic}
            #queues_provider: queues_provider_service
            queues:
                green-from-blu-integration-event:
                    name:     'green-from-blu-integration-event_qu'
                    callback: green_acl.from_blu.consumer.incoming_event
                    routing_keys:
                        - 'blu.#'
                green-from-red-integration-event:
                    name:     'green-from-red-integration-event_qu'
                    callback: green_acl.from_red.consumer.incoming_event
                    routing_keys:
                        - 'red.#'
