framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

            async: '%env(MESSENGER_TRANSPORT_DSN)%/async'
            async_2: '%env(MESSENGER_TRANSPORT_DSN)%/async2'


            consumer_async: '%env(MESSENGER_TRANSPORT_DSN)%/consumer_async'


        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

            #'App\Message\FooMessage': []
            'App\Message\BarAsyncMessage': [async, async_2, consumer_async]
